name: giphy_api_client
description: A Giphy API Client for Dart compatible Web, Flutter, and server-side dart
version: 0.1.3
homepage: https://github.com/java-james/giphy_client

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  meta: ^1.9.1
  http: ^1.0.0

dev_dependencies:
  test: 1.20.1
  mockito: 5.1.0
  coverage: 1.1.0
  build_runner: 2.1.7
  lints: ^1.0.1
